---
abstract: 'Delly Genomic Rearrangements Perl API'
author:
  - 'Richard de Borja <richard.deborja@sickkids.ca>'
build_requires:
  Data::Dumper: 0
  MooseX::ClassCompositor: 0
  Test::Exception: 0
  Test::Files: 0
  Test::Moose: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NGS-Tools-Delly
provides:
  NGS::Tools::Delly:
    file: lib/NGS/Tools/Delly.pm
    version: 0.01
  NGS::Tools::Delly::Roles::Base:
    file: lib/NGS/Tools/Delly/Roles/Base.pm
    version: 0
  NGS::Tools::Delly::Roles::Translocations:
    file: lib/NGS/Tools/Delly/Roles/Translocations.pm
    version: 0
requires:
  Carp: 0
  File::Basename: 0
  Getopt::Long: 0
  Moose: 0
  MooseX::Params::Validate: 0
  Pod::Usage: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.01
